import { Doc } from "../_generated/dataModel";
import { shuffle } from "./utility";

enum TimeAdvantage {
  Day = "DAY",
  Night = "NIGHT",
  Any = "ANY",
}

export type MonsterDeck = Doc<"gameState">["monsterDeck"];

const baseMonsterDeck: MonsterDeck = [
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Fairy",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Imp",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Sasquatch",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Leprechaun",
    timeAdvantage: "DAY",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Vampire",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Werewolf",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Banshee",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Kitsune",
    timeAdvantage: "NIGHT",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Mummy",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Golem",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Zombie",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Acting",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Dancing",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Comedy",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Dancing",
    secondaryAbility: "Singing",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Acting",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Comedy",
  },
  {
    id: "",
    monsterType: "Ghost",
    timeAdvantage: "ANY",
    primaryAbility: "Singing",
    secondaryAbility: "Dancing",
  },
];

const monsterDeck = [...baseMonsterDeck];

function shuffleMonsterDeck(deck: MonsterDeck): MonsterDeck {
  return (shuffle(deck) as MonsterDeck).map((card) => ({
    ...card,
    id: crypto.randomUUID(),
  }));
}

export function createShuffledMonsterDeck(): MonsterDeck {
  return shuffleMonsterDeck(Array.from(monsterDeck));
}
